export const ADD_USER_PRIVILEGE = 'ADD_USER_PRIVILEGE';
export const MODIFY_USER_PRIVILEGE = 'MODIFY_USER_PRIVILEGE';
export const DELETE_USER_PRIVILEGE = 'DELETE_USER_PRIVILEGE';

export const ADMIN_PRIVILEGE = 'ADMIN_PRIVILEGE';
