export const ADD_CHANNEL_PRIVILEGE = 'ADD_CHANNEL_PRIVILEGE';
export const MODIFY_CHANNEL_PRIVILEGE = 'ADD_CHANNEL_PRIVILEGE';
export const DELETE_CHANNEL_PRIVILEGE = 'DELETE_CHANNEL_PRIVILEGE';
export const ADD_MAPPING_PRIVILEGE = 'ADD_MAPPING_PRIVILEGE';
export const MODIFY_MAPPING_PRIVILEGE = 'MODIFY_MAPPING_PRIVILEGE';
export const DELETE_MAPPING_PRIVILEGE = 'DELETE_MAPPING_PRIVILEGE';
export const ADMIN_PRIVILEGE = 'ADMIN_PRIVILEGE';
