server:
  port: ${APP_PORT:9090}
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/manunin
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: /changelog/changelog-master.xml
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
#            redirectUri: "http://localhost:9090/test"
            redirectUri: "http://localhost:9090/api/v1/login/oauth2/code/google"
logging:
  level:
    org:
      springframework:
#        web: DEBUG
        security: DEBUG


#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true


springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
app:
  jwtSecret: secret
  jwtExpirationInMs: 86400000