export const ADD_GROUP_PRIVILEGE = 'ADD_GROUP_PRIVILEGE';
export const MODIFY_GROUP_PRIVILEGE = 'MODIFY_GROUP_PRIVILEGE';
export const DELETE_GROUP_PRIVILEGE = 'DELETE_GROUP_PRIVILEGE';
export const ADMIN_PRIVILEGE = 'ADMIN_PRIVILEGE';
export const DATE_FORMAT = 'DD.MM.YYYY HH:mm';


export const ADD_RULE = 'ADD_RULE';
export const MODIFY_RULE = 'MODIFY_RULE';
export const DELETE_RULE = 'DELETE_RULE';
