export const ADD_GROUP_PRIVILEGE = 'ADD_GROUP_PRIVILEGE';
export const MODIFY_GROUP_PRIVILEGE = 'MODIFY_GROUP_PRIVILEGE';
export const DELETE_GROUP_PRIVILEGE = 'DELETE_GROUP_PRIVILEGE';
export const ADMIN_PRIVILEGE = 'ADMIN_PRIVILEGE';
export const DATE_FORMAT = 'DD.MM.YYYY HH:mm';
