export const ADD_GROUP_PRIVILEGE = 'ADD_GROUP_PRIVILEGE';
export const MODIFY_GROUP_PRIVILEGE = 'MODIFY_GROUP_PRIVILEGE';
export const DELETE_GROUP_PRIVILEGE = 'DELETE_GROUP_PRIVILEGE';
export const ADMIN_PRIVILEGE = 'ADMIN_PRIVILEGE';
export const DATE_FORMAT = 'DD.MM.YYYY HH:mm';

export const ADD_ROLE_PRIVILEGE = 'ADD_ROLE_PRIVILEGE';
export const MODIFY_ROLE_PRIVILEGE = 'MODIFY_ROLE_PRIVILEGE';
export const DELETE_ROLE_PRIVILEGE = 'DELETE_ROLE_PRIVILEGE';
