export default {
  groups: '/groups',
  groupsCount: '/groups/groupsCount',
  schedules: '/schedules',
  resourceTypes: '/resource-types',
  calendars: '/calendars',
  users: '/auth',
  login: '/auth/signin',
  register: '/auth/signup',
  students: '/students',
  studentsByUrl: '/students/addByUrl',
  studentsCount: '/students/studentsCount',
  shortUrlsGetGroupId: '/shortUrls/getGroupId',
  shortUrlsGetGroupUrl: '/shortUrls/getGroupUrl',
  resources: '/resources',
  resourcesCount: '/resources/resourcesCount',
}
