export const ADD_RESOURCE_PRIVILEGE = 'ADD_RESOURCE_PRIVILEGE';
export const MODIFY_RESOURCE_PRIVILEGE = 'MODIFY_GROUP_PRIVILEGE';
export const DELETE_RESOURCE_PRIVILEGE = 'DELETE_GROUP_PRIVILEGE';
export const ADMIN_PRIVILEGE = 'ADMIN_PRIVILEGE';
