export const ADD_STUDENT_TO_GROUP_PRIVILEGE = 'ADD_STUDENT_TO_GROUP_PRIVILEGE';
export const MODIFY_STUDENT_IN_GROUP_PRIVILEGE = 'MODIFY_STUDENT_IN_GROUP_PRIVILEGE';
export const DELETE_STUDENT_FROM_GROUP_PRIVILEGE = 'DELETE_STUDENT_FROM_GROUP_PRIVILEGE';
export const ADMIN_PRIVILEGE = 'ADMIN_PRIVILEGE';

export const DATE_FORMAT = 'DD.MM.YYYY HH:mm';
