package com.manunin.auth.model;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;

@Entity
@Table(name = "app_users")
public class User {
    /**
     * JPA Annotation
     * 
     * @GeneratedValue must be used together with @Id, and can be specified with
     *                 different strategies, yet cannot manually set primary key:
     *                 1. IDENTITY (MySQL): the primary key is generated by database
     *                 auto-increment. (cannot do batch insert)
     *                 2. SEQUENCE (Oracle/PostgreSQL): the primary key is generated
     *                 by database sequence.
     *                 3. AUTO: the database automatically matches the best
     *                 strategy.
     *                 4. TABLE (all db): JPA self-maintains a table to simulate
     *                 sequential generation for primary key.(Worst perfomrance,
     *                 best compatibility)
     * 
     *                 If you want to manually set the primary key, do not use this
     *                 annotation
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    private String username;
    private String firstName;
    private String lastName;
    private String email;
    private String password;

    @Column(name = "IS_LOCKED")
    private boolean isLocked;

    /**
     * JPA Annotation
     * 
     * @ManyToMany: used to specify the relation between two tables, mapping the
     *              relation table into the object set.
     *              fetch keyword (FetchType.EAGER / FetchType.LAZY) is used to
     *              specify if to get the data immedaitely or in lazy mode.
     * @JoinTbale: specify the join operation to get the object set
     */
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "user_roles", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "role_id"))
    private Set<Role> roles = new HashSet<>();

    public User() {
    }

    public User(final String username, final String email, final String password) {
        this.username = username;
        this.email = email;
        this.password = password;
    }

    public User(final String username, final String email, final String password, final String firstName,
            final String lastName) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public User(long id, String username) {
        this.id = id;
        this.username = username;
    }

    public User(String username, String email, String firstName, String lastName, final boolean isLocked) {
        this.username = username;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.isLocked = isLocked;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isLocked() {
        return isLocked;
    }

    public void setLocked(boolean locked) {
        isLocked = locked;
    }

    public Set<Role> getRoles() {
        return Collections.unmodifiableSet(roles);
    }

    public void addRole(Role role) {
        roles.add(role);
    }

    public void setRoles(Set<Role> roles) {
        this.roles = new HashSet<>(roles);
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}
